version: '3.9'  # Define the version of Docker Compose

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydatabase  # Example DB connection string
      - REDIS_URL=redis://cache:6379  # Example Redis connection string
    volumes:
      - .:/app  # Mount the current directory to /app
    networks:
      - app-network
    depends_on:
      - db
      - cache

  db:
    image: postgres:13  # Use an official PostgreSQL image
    container_name: my_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - app-network

  cache:
    image: redis:alpine  # Use a lightweight Redis image
    container_name: my_cache
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db_data:  # Named volume for PostgreSQL data persistence

networks:
  app-network:  # Create a custom network for service communication