name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Update this if your default branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          repository: serverlesssalad/fast-python-mongo-demo
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/serverlesssalad/fast-python-mongo-demo/rapid:latest .

      # Step 5: Push the Docker image to GitHub Container Registry
      - name: Push Docker image
        run: |
          docker push ghcr.io/serverlesssalad/fast-python-mongo-demo/rapid:latest