name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Set the branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU for multi-platform builds (if needed)
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/serverlesssalad/fast-python-mongo-demo/dynamo:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/serverlesssalad/fast-python-mongo-demo/dynamo:latest